### ISSUE TITLE
Simple usage failure

### ISSUE THREAD

**Issue by jnccneto** [Theodeus/tuna#23]
Hi

Just trying the tuna.js features but cant seem to get the simple usage setup.
Im running this:

var context = new AudioContext();
var tuna = new Tuna(context);
       
    var chorus = new tuna.Chorus({
    rate: 1.5,
    feedback: 0.2,
    delay: 0.0045,
    bypass: 0
});

and getting this error:
Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': 1 argument required, but only 0 present.

something Im missing?

**Comment by Theodeus** [comment]
I can confirm this in version 0.3.0. I'll have a look!

**Comment by Theodeus** [comment]
Done! Use version 0.3.1 and you should be good to go!
