### ISSUE TITLE
Problem connecting nodes

### ISSUE THREAD

**Issue by errozero** [Theodeus/tuna#28]
I've created a test effect and tried to connect a gain node to its input. I receive the following error:

> "Failed to execute 'connect' on 'AudioNode': No function was found that matched the signature provided."

Here is an example of the code:

```javascript
var testFX = new app.tuna.Phaser({
    rate: 1.2,                     //0.01 to 8 is a decent range, but higher values are possible
    depth: 0.3,                    //0 to 1
    feedback: 0.2,                 //0 to 1+
    stereoPhase: 30,               //0 to 180
    baseModulationFrequency: 700,  //500 to 1500
    bypass: 0
});

this.masterGainNode.connect(testFX);
```
Have I done something wrong here? I can connect the masterGainNode to the destination fine. Also, I can do a console.log() on testFX and see that a tuna node has been created.

**Comment by Theodeus** [comment]
Hey!

If you are running an older version of Tuna you have to do

```javascript
    this.masterGainNode.connect(testFX.input);
```

If you're using v0.3.1 or above, I'll have to have a look at that..

**Comment by errozero** [comment]
I got a copy of the minified file a few days ago, just grabbed a fresh copy of it and it's now working fine.  Thanks.

**Comment by Theodeus** [comment]
Ah, great! That was my bad - I'd forgotten to update the minified file. Need to get some build process going. :) Great to hear that it works now, and as a bonus you've now got a Ping pong Delay in there. 

Cheers!
