### ISSUE TITLE
Can we export output ? 

### ISSUE THREAD

**Issue by muratgorken** [Theodeus/tuna#31]
Can we export output ?

**Comment by Theodeus** [comment]
Not via Tuna itself, but using https://github.com/mattdiamond/Recorderjs works seamlessly with Tuna! Also, there's a new native Media Recorder API that's coming, but support isn't great yet.. https://developer.mozilla.org/en/docs/Web/API/MediaRecorder_API

Hope that helps!

**Comment by muratgorken** [comment]
thanks, i studied recorderjs but as i know this needs play music from start to finish, Because i added effects to recorded music.
