### ISSUE TITLE
Some working links of Tuna.js

### ISSUE THREAD

**Issue by shivrajsa** [Theodeus/tuna#32]
I found some examples created by @Theodeus , may be useful for beginners like me.

[http://codepen.io/Theodeus/pen/WbmXgV?editors=0010](http://codepen.io/Theodeus/pen/WbmXgV?editors=0010)

Play some music with keyboard keys ( z,s,d,c . . etc)
[http://codepen.io/Theodeus/pen/EjLPrY](http://codepen.io/Theodeus/pen/EjLPrY)

**Comment by Theodeus** [comment]
Oh, I had forgotten I'd written those. :) It's probably a good idea to have those in there as quick "get me started"'s. 

Would you like to make a pull request with a section in the README with the links, @shivrajsa, or should I go ahead and add them?

**Comment by shivrajsa** [comment]
Please go ahead, I am not familiar with GitHub. There are very few working examples on web for Tuna.js.
