### ISSUE TITLE
Which effect should be used to change frequency of note while playing.

### ISSUE THREAD

**Issue by shivrajsa** [Theodeus/tuna#33]
I have developed an app using [MIDI.js](https://github.com/mudcube/MIDI.js), Tuna effects are supported in MIDI.js. I have requirement of changing frequency (Slightly) of note from its standard frequency while playing. Which Tuna effect will help to achieve this? 
If not Tuna, is there any other way?

**Comment by Theodeus** [comment]
The Flanger or Chorus will alter the frequency slightly, though I suspect it's not what you're looking for. Instead, I'd suggest you check out the playbackRate property of the audio source you're using (https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/playbackRate), which has the best support, or the detune property which is most likely exactly what you're looking for https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune.

**Comment by shivrajsa** [comment]
Thank you for your guidance, it really helped. I can use detune property in MIDI.js, here is example 
[MIDI webaudio js](https://github.com/mudcube/MIDI.js/issues/179)
