### ISSUE TITLE
Example with a mp3 file

### ISSUE THREAD

**Issue by dkdl** [Theodeus/tuna#35]
I checked this example: http://codepen.io/Theodeus/pen/WbmXgV?editors=0010
but I don't understand how I can adjust a normal mp3/ogg audio element. 

Is this possible?

**Comment by Theodeus** [comment]
Yes, that is possible, although it's not really a Tuna issue per se. You're looking for the audioContext.createMediaElementSource method, which will let you use an <audio> tag as source, and the rest is exactly the same as the example! Good luck!
