### ISSUE TITLE
Overdrive

### ISSUE THREAD

**Issue by remigio** [Theodeus/tuna#36]
I suggest line 518:
this.release = properties.release || this.defaults.release.value;
to be changed to:
this.release = initValue(properties.release, this.defaults.release.value);
otherwise the 0 value isn't managed properly.
Moreover. I think the line 647:
this.compNode.release = value / 1000;
should be
this.compNode.release.value = value / 1000;

**Comment by Theodeus** [comment]
Both seems true to me! Do you want to make a pull request with those fixes, or do you want me to go ahead and change it?

Cheers!

**Comment by remigio** [comment]
It's ok you going ahead and fix them. Thanks a lot for your excellent work!
Have a nice day!
