### ISSUE TITLE
Tremolo stereoPhase value not bindable due to get not returning correct value

### ISSUE THREAD

**Issue by DearthFunk** [Theodeus/tuna#37]
I could be totally wrong about this, but just noticed it when i was trying to build an angularJs app using Tremolo. 
https://github.com/Theodeus/tuna/blob/master/tuna.js#L1643 
This line should be returning this._stereoPhase not this._rate.

**Comment by Theodeus** [comment]
Yes, that does seem sketchy. :) Do you want to create a pull request, @DearthFunk, or should I go ahead and change that?
