### ISSUE TITLE
PingPongDelay Limit

### ISSUE THREAD

**Issue by selfrefactor** [Theodeus/tuna#38]
Hello Oskar,

It appears that there is additional zero in your docs in regards to PingPongDelay
It reads:
`    delayTimeLeft: 150, //1 to 10000 (milliseconds)
    delayTimeRight: 200 //1 to 10000 `
while it should be:
`    delayTimeLeft: 150, //1 to 1000 (milliseconds)
    delayTimeRight: 200 //1 to 1000 `

**Comment by Theodeus** [comment]
Hm.. not sure that's right. 

It does say 10,000 is the maximum at line 1518 in tuna.js. Did it behave differently somehow?

**Comment by selfrefactor** [comment]
When I use values over 1000, I receive I warning that only values between 0 and 1 are accepted. Then I look the code and I found the following line:
`set: function(value) {
                this._delayTimeLeft = value;
                this.delayLeft.delayTime.value = value / 1000;
            }`
So I set the max value to 1000 instead of 10000 and the warning message disappeared. Then I opened this issue.
If you don't get warnings when you set values above 1000, then it must be issue related to the browsers. I use the latest Chrome. Are you on Chrome as well?

**Comment by Theodeus** [comment]
Ah, now I see! That's a new bit of the Web Audio spec that I wasn't aware of! Basically, one has to supply a max delay time when creating the delay nodes, or else Web Audio will default to 1 second which is what's happening in tuna right now. Great catch, thanks! Will fix asap.

https://www.w3.org/TR/webaudio/#widl-BaseAudioContext-createDelay-DelayNode-double-maxDelayTime

**Comment by Theodeus** [comment]
This fixes this issue. I think there are more effects that might be affected by this as well, but I'll check those separately. Thanks @selfrefactor for bringing this up!
