### ISSUE TITLE
Make Tuna fully compatible with bundled applications

### ISSUE THREAD

**Issue by alexanderwallin** [Theodeus/tuna#39]
Hey!

I just started to check out this package, and I'm very excited about it. :)

I use Webpack to bundle my app, but importing Tuna causes the self-invoking function to receive a `window` argument that is not the browser's `window`. This leads to `window.[webkit]AudioContext` being undefined, and the module will exit with an error if no `context` argument is passed.

```js
import Tuna from 'tunajs'

const tuna = new Tuna()
// Will throw "Tuna cannot initialize because this
// environment does not support web audio", although
// it's executed in the browser
```

**Comment by alexanderwallin** [comment]
Clarified title, since it works when passing a `context` argument

**Comment by Theodeus** [comment]
Gotcha! Will have to look into this when time allows! :)

**Comment by Theodeus** [comment]
Ugh - do you have a hunch on how to fix this @alexanderwallin?

**Comment by alexanderwallin** [comment]
I think if we just rename the `window` argument to `_window`, we can separate exporting and context creation. I'll fire off a PR in a sec. :)

**Comment by alexanderwallin** [comment]
Okay, see #41
