### ISSUE TITLE
Which effects should be used to create concert hall effect?

### ISSUE THREAD

**Issue by shivrajsa** [Theodeus/tuna#42]
Can anybody guide which effect can be used create concert hall effect, or where output comes from microphone with some mixing effect

**Comment by alexanderwallin** [comment]
I think the right approach is to use a `Convolver`, passing a concert hall impulse response audio file as `impulse`.

At the bottom of this article is a list of resources: https://www.ableton.com/en/blog/convolution-reverb-impulse-responses/. Perhaps you can find something there!

**Comment by shivrajsa** [comment]
@alexanderwallin Thank you. Is there any other way, because using IR file for every note seems CPU expensive

**Comment by Theodeus** [comment]
There's no other way native to Web Audio, or Tuna, but I suppose you could write your own reverb effect using a script processor (or audio worker once those are released). I would think, however, that that would be a bigger CPU hit than using the native convolver (which Tuna uses in the Convolver effect).

Don't create a separate Convolver per note though, route all notes to the same Convolver and you should be fine (though convolution on mobile devices are almost always a no-go..)

**Comment by shivrajsa** [comment]
@Theodeus Than you, I didnt strike, we can set it once.
