### ISSUE TITLE
Create utility effects for easier chaining

### ISSUE THREAD

**Issue by alexanderwallin** [Theodeus/tuna#43]
When building effect chains, it would be handy to be able to use Tuna all the way. I suggest adding a `Panner` (based on `StereoPannerNode`) and a simple `Gain` (`GainNode`).

This would:

* (to greater extent) enable us to avoid mixing different methods of creating effects;
* (to greater extent) unify param assignment syntax (e.g. no mixed `effect.param.value = val` and `effect.param = val`); and
* provide useful functionality like bypassing and automation to these two effects.

What do you think? I'd be happy to submit a PR!

**Comment by Theodeus** [comment]
Sounds great!

**Comment by Theodeus** [comment]
Fixed in eb460e0affd5df32ac9c38fb7c30428a1d034784
