### ISSUE TITLE
Tuna features

### ISSUE THREAD

**Issue by berserk82** [Theodeus/tuna#52]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I wonder if Tuna supports the following effects:
bass boost
delay
waveshaper
amplifier
chorus
compressor
equalizer
noise gate
flanger
phaser
sidechaining (with or without compressor)
limiter
vocoder

Thanks in advance for any help.

Bye, Ivano.

**Comment by alesaccoia** [comment]
you can find the list of the effects in the home page of the project, just scroll down and read the README.
https://github.com/Theodeus/tuna
