### ISSUE TITLE
Using Tuna with plain HTML

### ISSUE THREAD

**Issue by berserk82** [Theodeus/tuna#53]
Hello there again.
I wonder if I can use Tuna with plain HTML, without Node/js or any framework.

Thanks in advance for any help.

Bye, Ivano.

**Comment by Theodeus** [comment]
Hey!

Yes, just download tuna.js (or tuna-min.js if you want a smaller version) and import it like any other script via the script tag

```
<script src="tuna.js"></script>
```

You can then access the library via `window.Tuna`

I hope that helps!
