### ISSUE TITLE
Please, add  some effects

### ISSUE THREAD

**Issue by berserk82** [Theodeus/tuna#54]
Hello there again.
After my request to list available effects was responsed, I'm still missing the following effects:
bass boost
waveshaper
chorus
equalizer
noise gate
flanger
sidechaining
limiter
vocoder

Please, add them.

Thanks in advance for either.

Bye, Ivano.

**Comment by alexanderwallin** [comment]
Chorus already exists. As for the others, they are a lot of work, and a plain order like that is not very compelling to start working on.

Is there one of them you want or need the most? Could you supply a use case?

**Comment by berserk82** [comment]
No, I don't have an order ATM.
I just wish in the future these will be available.

**Comment by alexanderwallin** [comment]
Would you mind sharing what you would be using them for? 😊

**Comment by berserk82** [comment]
I would compose music with them, with wad.js as well

**Comment by Theodeus** [comment]
Hey!

This is a nice list to keep around for the future, so thanks!

Until the day comes when these have been added, here's a few tips on how to achieve some of these today:

Flanger - this is basically a chorus with a really small delay, so try creating a Tuna Delay node and set the delay property to something small and see if you can get the effect you want. (http://makingmusicmag.com/difference-between-phase-flanger-and-chorus-effect/)

Bass boost - this should be achievable with the Filter node. Set the filterType property to "lowshelf" and the gain to a positive number and you should get a bass boost. Adjust the frequency and Q to your liking. :)

Equalizer - this could be achieved by linking Filter nodes. Here's a SO answer that I wrote way back on how to achieve a 3-band EQ, using pure Web Audio, but the same could be achieved with the Tuna Filter node: http://stackoverflow.com/questions/13794284/implementing-a-3-band-equalizer-using-web-audio-api/13797510#13797510

Noise gate - there's actually a pull request for this from @alexanderwallin! It's just awaiting some feedback from contributors before we merge it, but you should be good to start using it today!

Waveshaper - there is a native waveshaper that you could use: https://developer.mozilla.org/en-US/docs/Web/API/WaveShaperNode

**Comment by berserk82** [comment]
Interesting sir, thanks so much

**Comment by berserk82** [comment]
Now that I have much more experience in sound synthesis and processing, I can tell 2 things:
1) The list is actually almost pointless (these effects are not only not required, but generally shoud be avoided)
2) The only *real* needed effect on the list would be the limiter, better if with selective frequencies (as the compressor tough)

If you'll just add it (and if needed, add a frequency parameter for compression), I would thank you so much.

**Comment by tencircles** [comment]
Since you're so much more experienced now, feel free to put in a pull request containing your multiband compressor.

**Comment by berserk82** [comment]
I didn't say I'm also a developer yet.
Thanks anyhow.

**Comment by berserk82** [comment]
Just realized I wrote a mistake. Limiter is actually the same as compressor, with different names for the same parameters.
Is the compressor already able to do compression on a selected frequency? Or is it "general" (the whole spectrum) ?
