### ISSUE TITLE
Tuna doesn't work in FIrefox and Chrome

### ISSUE THREAD

**Issue by berserk82** [Theodeus/tuna#55]
Hello everyone.
I tried to open the Tuna demo in Firefox and Chrome, both locally and on a webserver, but it shows me a message saying the web audio API is not supported, and to download Chrome to enjoy the demo.
Note I'm on Linux.

Thanks in advance for either.

Bye, Ivano.

**Comment by alexanderwallin** [comment]
What Linux version and browser versions are you testing it in?

**Comment by berserk82** [comment]
I'm on Debian Sid (latest, unstable) with the latest Firefox and Chrome.

**Comment by berserk82** [comment]
Chrome 58.0.3029.110 (64-bit)
Firefox 45.9.0

**Comment by berserk82** [comment]
P.S.: I'm not using Node. Is that required?

**Comment by alexanderwallin** [comment]
Node is for running JavaScript outside the browser, so no it is not required.

**Comment by Theodeus** [comment]
I'll check on my linux machine in a while and see if I have the same issue.

Do you get any errors in your javascript console, @berserk82?

**Comment by berserk82** [comment]
I don't know, I'll let you know ASAP

**Comment by berserk82** [comment]
Yes, but the demos are changed. If I run offline-runner.html from tests I get errors in the console complaining I don't have jasmine.

**Comment by Theodeus** [comment]
Aha, that makes sense then. :) The demo branch hasn't seen development for the last 5 years, and the Web Audio API has fundamentally changed in that time, so I don't expect anything in that branch to work, and there's no intent to make it work as of now. 

The current demo (that hopefully should work for you) is http://codepen.io/Theodeus/pen/oxKjmy?editors=0010

**Comment by berserk82** [comment]
How can I download it?

**Comment by Theodeus** [comment]
There's a green button towards the upper right corner on this page that says "clone or download" -> https://github.com/Theodeus/tuna
