### ISSUE TITLE
Building blocks

### ISSUE THREAD

**Issue by mrrm92** [Theodeus/tuna#56]
Does tuna provide the building blocks listed here?
https://dsp.stackexchange.com/questions/2475/what-are-the-basic-categories-of-operations-performed-on-audio-signals-to-create/2478#2478

**Comment by tencircles** [comment]
The web audio API provides those blocks, the effects in Tuna.js are built from those blocks. If you're interested in building synths, the base API has everything you need. If you give a bit more info on what you're trying to do I might be able to point you in the right direction.

**Comment by mrrm92** [comment]
Nothing more than (indeed) build modular synths.
Thanks a lot for your help, I never wouldn't even imagine this could be possible with Tuna.
The fact is I come from "trying to learn puredata" with a lot of frustration.
I just hope to understand better using Tuna.
