### ISSUE TITLE
Phaser values can start throwing errors

### ISSUE THREAD

**Issue by Theodeus** [Theodeus/tuna#59]
When increasing both depth and baseModulationFrequency the Phaser can start acting up. 

    BiquadFilter.frequency.value 130024 outside nominal range [0, 24000]; value will be clamped.

    tuna.js?122:1510 Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
         at value (tuna.js?122:1510)
         at ScriptProcessorNode.<anonymous> (tuna.js?122:2242)

**Comment by Theodeus** [comment]
To reproduce;
depth: 1
baseModFreq: 500

Not sure about line 1544 either. Shouldn't this call the depth setter so that the LFO oscillation updates? 

     this._depth = this._depth;

**Comment by Theodeus** [comment]
Though I expect the error I saw was due to bad testing code. The clamping message is still an issue.

**Comment by richtier** [comment]
I get this error with the following options:

```
baseModulationFrequency="700",
bypass=true
depth="0.6"
feedback="0.7"
rate="0.1",
stereoPhase="40",
```
oddly even with bypass true

**Comment by Theodeus** [comment]
I'll have to look at this!

**Comment by richtier** [comment]
I'll create a separate ticket for the `bypass` issue as some clarification would be helpful for me.

**Comment by richtier** [comment]
The problem was because I was using string values, not numbers

similar to [this issue](https://github.com/Theodeus/tuna/issues/58)

perhaps this issue can be closed too?
