### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [Theodeus/tuna#61]
Hello,

I'm using Tuna in one project and I got some deprecations, let me know if I can help to fix it:

**[Deprecation]** Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

**[Deprecation]** DelayNode.delayTime.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**[Deprecation]** AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.

**[Deprecation]** GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**[Deprecation]** BiquadFilterNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**[Deprecation]** BiquadFilterNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**[Deprecation]** BiquadFilterNode.Q.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by Theodeus** [comment]
Thanks Rodrigo!

I'm aware that these are showing up. I was planning to update these calls when we start splitting the code base into separate files.

However, if you feel like it, I'd be happy to get a pull request with a fix. :)

Btw. I don't think the first warning about styling originates from Tuna.

Cheers!
