### ISSUE TITLE
Pitch shift node 

### ISSUE THREAD

**Issue by richtier** [Theodeus/tuna#65]
I have written a pitch shift piece of code.

It changes the pitch of the sample without affecting the playback rate. 

Is this of interest? I can contribute it if so.

**Comment by alexanderwallin** [comment]
Sounds wicked if you ask me!

**Comment by Theodeus** [comment]
I'd say the same! :) A PR would be most welcome!

**Comment by richtier** [comment]
PR up: https://github.com/Theodeus/tuna/pull/67
