### ISSUE TITLE
Tests failing in master

### ISSUE THREAD

**Issue by richtier** [Theodeus/tuna#68]
There are 10 failing tests in master.

I do not have enough exposure to the codebase to identify if the tests are wrong or the code is wrong.

![image](https://user-images.githubusercontent.com/5485798/52169414-d7dc5c80-272f-11e9-8ed2-369b8b642bb0.png)

**Comment by Theodeus** [comment]
Fixed.

The AudioContext was created without user interaction, which was the first part of the issue. The second part was the smoothing that I implemented to avoid deviating from the previous behavior in Web Audio (where values were auto smoothed) - this didn't finish in time for the tests to pass when Jasmine ran the checks.
