### ISSUE TITLE
It would be helpful if the wiki showed defaults

### ISSUE THREAD

**Issue by richtier** [Theodeus/tuna#69]
the wiki for nodes does not show defaults (or it's showing old defaults that have now changed)

e.g. Chrorus feedback in wiki shows 0.2 but the default in the code is 0.4.

Reading the documentation should be really helpful to see the defaults.

If the wiki should indeed show defaults I'm happy to update them.

**Comment by Theodeus** [comment]
Sounds like a great idea! Feel free to update. :)

**Comment by Theodeus** [comment]
I've updated the values in the wiki to reflect the defaults in Tuna, and added a comment for clarity. :)
