### ISSUE TITLE
Update codepen example

### ISSUE THREAD

**Issue by Theodeus** [Theodeus/tuna#71]
Have moved my personal site to github pages, so oskareriksson.se no longer points to the server with the example audio file.

**Comment by JiLiZART** [comment]
Also, need to avoid autoplay policy `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`

**Comment by Theodeus** [comment]
Fixed. The autoplay policy is a real pain in the behind. 😓
