### ISSUE TITLE
Documentation for Delay

### ISSUE THREAD

**Issue by fallais** [Theodeus/tuna#77]
Hello, thanks a lot for your great work !
Is the documentation up to date regarding the delay please ?
I had to modify the code because the log tell me that delay time must be between 1 and 10. But the documentation says the contrary.

```js
var delay = new tuna.Delay({
    feedback: 0.45,    //0 to 1+
    delayTime: 150,    //1 to 10000 milliseconds
    wetLevel: 0.25,    //0 to 1+
    dryLevel: 1,       //0 to 1+
    cutoff: 2000,      //cutoff frequency of the built in lowpass-filter. 20 to 22050
    bypass: 0
});
```

Thanks !

**Comment by Theodeus** [comment]
Hey!

So sorry for the late reply, light years after you needed an answer. But anyway - the documentation is correct! What you see in your error message is time in seconds. Web Audio wants you to set time in seconds, from 0 to 10, while Tuna takes milliseconds and convert it under the hood to seconds for you. 

Hopefully that clarifies why you're getting that warning. :)
