### ISSUE TITLE
Overdrive algorithm issue

### ISSUE THREAD

**Issue by setalosas** [Theodeus/tuna#83]
Hi, I noticed a possible small bug in the second algorithm of Overdrive. If you have a look at the generated curves, it's easy to spot (however it doesn't sound _that_ bad :-)

![image](https://user-images.githubusercontent.com/21111643/111922184-bd44d900-8a98-11eb-9384-9b35ccaa5014.png)

The incriminated line is:

`y = ((0.5 * Math.pow((x + 1.4), 2)) - 1) * y >= 0 ? 5.8 : 1.2;`

And the correct version is:

`y = ((0.5 * Math.pow((x + 1.4), 2)) - 1) * (y >= 0 ? 5.8 : 1.2);`

Just a precedence.

**Comment by Theodeus** [comment]
Great catch! :) 

Thanks a bunch for pointing it out, and a bunch of apologies as well for responding mooonths later!
