### ISSUE TITLE
Mixdown bug candidate in EnvelopeFollower

### ISSUE THREAD

**Issue by setalosas** [Theodeus/tuna#84]
Hi, sorry for bringing this up, but this one remained unnoticed in the EnveloperFollower as it's always called with mono signal:

```
   compute: {
   ...
                chan = rms = i = 0;
                if (channels > 1) { //need to mixdown
                    for (i = 0; i < count; ++i) {
                        for (; chan < channels; ++chan) {
                            current = event.inputBuffer.getChannelData(chan)[i];
                            rms += (current * current) / channels;
                        }
                    }
              ...
```
chan should be reinitialized in every loop: 

```for (let chan = 0; chan < channels;...```

or you'll get a weaker signal (/2) and a much weaker sweep as result at the end.

(It's not a bug technically as the input is always mono, but maybe this could change in the future.)

**Comment by setalosas** [comment]
So a cleaner and more optimized version without the if ... else would be like:

```
  for (let chan = 0; chan < channels; ++chan) {
      for (let i = 0; i < count; ++i) {
          const current = event.inputBuffer.getChannelData(chan)[i]
          rms += current * current
       }
    }
    rms /= channels
```

**Comment by Theodeus** [comment]
Another excellent find! :) Thank you!!
