### ISSUE TITLE
connect html audio

### ISSUE THREAD

**Issue by eetsceeck1** [Theodeus/tuna#89]
Hi,
can you help me please?
i am trying to connect a simple html audio
no success so far, 
can you tell me what am i doing wrong? 
many thanks in advance!

here is my code:

<!DOCTYPE html>
<html>
<head>
</head>
<body>

<audio id="ddd" crossOrigin="anonymous" autoplay controls preload="none" src="test.mp3"></audio>

<script src="./tuna.js"></script>

<script>

var context = new AudioContext();

let HTMLAudioElement = document.getElementById("ddd");

var source = context.createMediaElementSource(HTMLAudioElement);

var tuna = new Tuna(context);

var chorus = new tuna.Chorus({
    rate: 1.5,
    feedback: 0.2,
    delay: 0.0045,
    bypass: 0
});

	var input = source.createGain();
	var output = source.createGain();
	input.connect(chorus);
	chorus.connect(output);
 
</script>
</body>
</html>

![notepad++_oJWenJttxe](https://user-images.githubusercontent.com/43915916/179370281-f2f22042-fe9c-4f0b-a5be-14008088c5c5.png)
![chrome_ARUqpx5i0P](https://user-images.githubusercontent.com/43915916/179370384-33fb7fcc-d404-4366-94bb-75be23fba6fe.png)

**Comment by rowild** [comment]
I am not a pro in web audio, but according to this docu
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createGain

`createGain` has to be used on audioContext. In your example that would be:

```js
const input = context.createGain()
const output = context.createGain()
```

**Comment by eetsceeck1** [comment]
Hi robert, 
thank you for your reply and trying to help, 
i am familiar with the audio api, the problem with tuna is there are two nodes (looks like) what we need to connect, it was confuses me, its the first time i messing with two nodes in one function what need to be connected to the same audiocontext the "input" and the "output"
more than a month i am searching the whole web for an answer, i couldn't find anything what can provide me a hint, last night i were trying to figure out the logic finally after several hours i successfully created a connection for tuna, the example i did post above its just the test folder i have created in trying to figure it out, but that actually goes to my project supposedly,

now finally the connection goes that way: 

`let audioContext = new AudioContext() || window.AudioContext || window.webkitAudioContext();

let audio = document.getElementById("PlayBackAudioElement");

let source = audioContext.createMediaElementSource(audio);

let tunabutton = document.querySelector("#tunabtn");

tunabutton.addEventListener("click", function () {

var convolver = new tuna.Convolver({
    highCut: 22050,                         //20 to 22050
    lowCut: 20,                             //20 to 22050
    dryLevel: 1,                            //0 to 1+
    wetLevel: 0.60,                         //0 to 1+
    level: 1,                               //0 to 1+, adjusts total output of both wet and dry
    impulse: "impulses/impulse_rev.wav",    //the path to your impulse response
    bypass: 1
});

var input = audioContext.createGain();

var output = audioContext.createGain();

input.connect(convolver);

convolver.connect(output);

source.connect(convolver);

convolver.connect(audioContext.destination);

});`

HTML:
`<audio id="PlayBackAudioElement" autoplay controls crossorigin="anonymous" preload="none">
<source src="">
</audio>`

maybe it will help to somebody in the future and i think this example need to be presented on the wiki, 

i did check the live demo also on codepen and i saw there the connection is pretty similar t mine, i did check the demo code before but for some reason i didn't saw it, it definitely could give me a hint, maybe i didn't saw it cause the case is different than mine, i have a music and radio player what include two visualizers and recorder, and the source is an array, not (on change) function with input and pre defined one file


![notepad++_ldAbhaQaet](https://user-images.githubusercontent.com/43915916/179480050-dadfaf2f-dfbe-4058-851c-483b09ab7df6.png)

**Comment by rowild** [comment]
Great that you found a solution! – BTW: You can get nicer code formatting if you put your code within 3 backticks and a language indicator: 

\`\`\`js
[your code]
\`\`\`

followed by a language indicator, here "js" or "javascript". One tick is only useful for one-liners and inline code.

// HTML
```html
<audio id="PlayBackAudioElement" autoplay controls crossorigin="anonymous" preload="none">
  <source src="">
</audio>
```

// JS
```js
let audioContext = new AudioContext() || window.AudioContext || window.webkitAudioContext();
let audio = document.getElementById("PlayBackAudioElement");
let source = audioContext.createMediaElementSource(audio);

let tunabutton = document.querySelector("#tunabtn"); // you should add this button to your html example
tunabutton.addEventListener("click", function () {
  var convolver = new tuna.Convolver({
    highCut: 22050, //20 to 22050
    lowCut: 20, //20 to 22050
    dryLevel: 1, //0 to 1+
    wetLevel: 0.60, //0 to 1+
    level: 1, //0 to 1+, adjusts total output of both wet and dry
    impulse: "impulses/impulse_rev.wav", //the path to your impulse response
    bypass: 1
  });

  let input = audioContext.createGain();
  let output = audioContext.createGain();
  
  input.connect(convolver);
  convolver.connect(output);
  
  source.connect(convolver);
  convolver.connect(audioContext.destination);
});
```

I have no idea what you want to achieve with your project, but are you sure you want to create a new convoler and new gains on each click on the tunabutton? And new gains on input/output? You'll create new instances each time you click the button...

**Comment by eetsceeck1** [comment]
Oh great, thanks!!! for the the explanation about to beautify codes on github, i didnt knew that, 
my new problem is how i disconnect (stopping) tuna effect on click now, i have a clue on the codepen demo but its not clear and i didn't test it yet, 
to get some indication about my project please visit my development folder:
http://epnetwork.cf/MRPRadioS100/vis/WYSIWYG/ProjectPublish/

what i am trying to achieve is to make a button what will start convolver and the same button will also will stop convolver, the same principle with the other effects, actually just convolver, delay, and gain, i dont need more than that, 
if you visit my project please close all the opened windows by clicking on the right top corner x button and then, you can play a radio by clicking on the left top corner button or mp3 music 
clicking on the right bottom "music" note icon,

the convolver will start by clicking on the "record" button in the middle, 
i took out the record function for testing the convolver till i will create a button for it,

**Comment by eetsceeck1** [comment]
found the solution, 
simply with ordinary audio api disconnect();

```js
[var dry = document.getElementById("dry"); //DISCONNECT BUTTON (SELECTOR)

dry.addEventListener("click", function(e) {

	convolver.disconnect();
	
});]
```

**Comment by eetsceeck1** [comment]
CLEAR EXPLANATION, MAYBE THIS WILL BE USEFUL MUCH MORE IF IT WILL BE PASTED ON THE WIKI. 

```html
<!-- HTML -->
<audio id="PlayBackAudioElement" autoplay controls crossorigin="anonymous" preload="none">
<source src="">
</audio>

<button id="EnableConvolverButton">Enable Convolver</button>
<button id="DisableConvolverButton">Disable Convolver</button>
<!-- END OF HTML -->
```

```js
//JAVASCRIPT
//
//	AUDIO CONTEXT.
let audioContext = new AudioContext() || window.AudioContext || window.webkitAudioContext();

//	SET VARIABLE FOR YOUR AUDIO ELEMENT.
let audio = document.getElementById("PlayBackAudioElement");

//	SET SOURCE VARIABLE - THE HTML AUDIO ELEMENT WILL BE YOUR SOURCE (MUSIC SOURCE/STREAM)
let source = audioContext.createMediaElementSource(audio);

//	SET VARIABLE FOR ENABLING THE EFFECT BUTTON (CONVOLVER IN THIS CASE)
let ConvolverEnableButtonVariable = document.querySelector("#EnableConvolverButton");

//	SET VARIABLE FOR DISABLING THE EFFECT BUTTON (CONVOLVER IN THIS CASE)
let ConvolverDisableButtonVariable = document.querySelector("#DisableConvolverButton");

//	THESE PARAMETERS BETTER TO BE OUTSIDE THE FUNCTION SO THEY WILL BE EXECUTED ON LOAD =>
//	
//	SET VARIABLE FOR TUNA NODE WITH YOUR EXIST AUDIOCONTEXT (THE AUDIOCONTEXT ABOVE)
//	NOTE: ***** IF YOU HAVE MORE NODES SUCH AS VISUALIZERS, YOU SHOULD ALWAYS USE THE SAME AUDIO CONTEXT *****
var tuna = new Tuna(audioContext);

//	CONVOLVER EFFECT
var convolver = new tuna.Convolver({
    highCut: 22050,                         //20 to 22050
    lowCut: 20,                             //20 to 22050
    dryLevel: 1,                            //0 to 1+
    wetLevel: 2.1,                          //0 to 1+
    level: 0.5,                             //0 to 1+, adjusts total output of both wet and dry
    impulse: "impulses/impulse_rev.wav",    //the path to your impulse response
    bypass: 0
});

//	INPUT AND OUTPUT CREATE GAIN ON THE WEB AUDIO API FOR TUNA (CAN BE ANY VARIABLE NAMES WE WANT OTHER THAN "INPUT" OR "OUTPUT")
///	MORE INFORMATION CAN BE FOUND HERE: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createGain
var input = audioContext.createGain();
var output = audioContext.createGain();

//	START EFFECT BUTTON
//	ON CLICK FUNCTION TO ENABLE CONVOLVER EFFECT.
ConvolverEnableButtonVariable.addEventListener("click", function () {

	input.connect(convolver);
	
	convolver.connect(output);
	
	source.connect(convolver);
	
	convolver.connect(audioContext.destination);

});


//	STOP EFFECT BUTTON
//	ON CLICK FUNCTION TO DISABLE CONVOLVER EFFECT.
ConvolverDisableButtonVariable.addEventListener("click", function(e) {

	convolver.disconnect();
	
});
```

**Comment by Theodeus** [comment]
Hey [eetsceeck1](https://github.com/eetsceeck1)!

I'm happy you found your answer. :) 

Tuna nodes mimics the API of regular Web Audio API nodes, so as long as you make sure you get your connections right, they work just the same (as you eventually figured out). I want to keep the explanation on the Wiki and Demo as bare-bones as possible, but I'll add some additional comments to the output/input nodes, which I see confused you! Thank you for your suggestion. :)

**Comment by eetsceeck1** [comment]
Thank you!
